version: "3.9"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./plugins:/opt/airflow/plugins
    - ./config:/opt/airflow/config
  depends_on:
    - airflow-db
  networks:
    - dwh_airflow

services:
  
  #airflow services
  airflow-db:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - 4040:5432
    networks:
      - dwh_airflow
  
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-scheduler

  airflow-scheduler:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Viet --lastname Lam --role Admin --email vietlam050607@gmail.com --password admin && airflow scheduler"
  
  mysql-db-source:
    image: mysql
    container_name: mysql-db-source
    volumes:
      - mysql_h:/var/lib/mysql
      - ./dataset:/tmp/dataset
      - ./load_dataset_into_mysql:/tmp/load_dataset
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=olist
      - MYSQL_ROOT_USER=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - dwh_airflow

  dwh-db:
    image: postgres:latest
    container_name: dwh-db
    hostname: dwh-db
    volumes:
      - postgres_data_h:/var/lib/postgres/data
      - ./pg_hba.conf:/tmp/pg_hba.conf
    command: ["postgres", "-c", "hba_file=/tmp/pg_hba.conf"]
    expose:
      - "3005"
    ports:
      - "3005:5432"
    env_file: airflow.env
    networks: 
      - dwh_airflow

  minio:
    hostname: minio_british
    image: minio/minio:latest
    container_name: minio_british
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data_s3:/data
    environment:
      MINIO_ROOT_USER: vietlam
      MINIO_ROOT_PASSWORD: 20022003
    command: server /data --console-address ":9001"
    networks:
      - dwh_airflow

networks:
    dwh_airflow:
volumes:
  mysql_h: {}
  postgres-db-volume:
  postgres_data_h: {}
